### ISSUE TITLE
support for non public github URL

### ISSUE THREAD

**Issue by furlongm** [j0057/github-release#55]
It would be a a good feature to be able to specify a private github URL rather than hardcoding the URL. The default should still be github.com

**Comment by jcfr** [comment]
Thanks for the suggestion

Are you talking about this URL:

https://github.com/j0057/github-release/blob/0080628236071800ac88b2f596a66bf056cf7a67/github_release.py#L24

And by "private" to you mean the case of on premise GitHub deployment ? Or private repo ? (Private repo hosted on github.com should already be supported)

**Comment by furlongm** [comment]
By private I mean on-premise GitHub deployment. It currently works but I need to manually change L24. An option would be great.

**Comment by jcfr** [comment]
Makes sense.  If you would like to contribute the change, I can help move it forward. 


Here are few possible approaches:

* approach 1: Change line 24 and update documentation accordingly. 

```
GITHUB_API = os.environ.get("GITHUB_API_URL", "https://api.github.com")
```


* approach 2:

  * this is more involved as it requires to associate the github_api_url with the context object passed between command, like what is done for repo_name [here](https://github.com/j0057/github-release/blob/0080628236071800ac88b2f596a66bf056cf7a67/github_release.py#L214). Instead of setting the repo_name as object, we would have a dict like `{'repo_name': ...., `github_api_url`: ...}`

   * The gist is to add an option named `--github-api-url` similar to `--github-token`

https://github.com/j0057/github-release/blob/0080628236071800ac88b2f596a66bf056cf7a67/github_release.py#L174-L175
